In [1]:
import pandas as pd
import io
import numpy as np
import seaborn as s
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/home/vimalkumar/Downloads/sonar_dataset.csv',header=None)

In [3]:
df

0       1       2       3       4       5       6       7       8   \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

         9   ...      51      52      53      54      55      56      57  \
0    0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1    0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2    0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3    0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4    0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
203  0.2684  ...  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065  0.0115   
204  0.2154  ...  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034  0.0032   
205  0.2529  ...  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140  0.0138   
206  0.2354  ...  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034  0.0079   
207  0.2354  ...  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040  0.0036   

         58      59  60  
0    0.0090  0.0032   R  
1    0.0052  0.0044   R  
2    0.0095  0.0078   R  
3    0.0040  0.0117   R  
4    0.0107  0.0094   R  
..      ...     ...  ..  
203  0.0193  0.0157   M  
204  0.0062  0.0067   M  
205  0.0077  0.0031   M  
206  0.0036  0.0048   M  
207  0.0061  0.0115   M  

[208 rows x 61 columns]

In [4]:
x = df.iloc[:,:-1]

In [5]:
x.shape

(208, 60)

In [6]:
y = df.iloc[:,-1]

In [7]:
y.shape

(208,)

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [9]:
y = le.fit_transform(y)

In [10]:
y[:5]

array([1, 1, 1, 1, 1])

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=8,test_size=0.15)

In [13]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((176, 60), (176,), (32, 60), (32,))

In [14]:
import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout


2021-12-28 10:58:17.225407: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-12-28 10:58:17.225447: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [15]:
(31+1)/2

16.0

In [16]:
model = Sequential()
model.add(Dense(units=32,activation='relu',kernel_initializer='uniform',input_dim=60))
model.add(Dense(units=32,activation='relu',kernel_initializer='uniform'))
model.add(Dropout(0.25))
model.add(Dense(units=16,activation='relu',kernel_initializer='uniform'))
model.add(Dropout(0.25))
model.add(Dense(units=1,activation='sigmoid',kernel_initializer='uniform'))

2021-12-28 10:58:32.033826: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-12-28 10:58:32.033859: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-12-28 10:58:32.033879: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (IG154): /proc/driver/nvidia/version does not exist
2021-12-28 10:58:32.034058: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [19]:
model.compile(
loss = 'binary_crossentropy',
#optimizer = 'SGD',
metrics = 'Accuracy')

In [20]:
model.fit(x_train,y_train,verbose=True,epochs=100,batch_size=2)

Epoch 1/100
88/88 [==============================] - 1s 1ms/step - loss: 0.6933 - Accuracy: 0.5057
Epoch 2/100
88/88 [==============================] - 0s 1ms/step - loss: 0.6931 - Accuracy: 0.5114
Epoch 3/100
88/88 [==============================] - 0s 1ms/step - loss: 0.6922 - Accuracy: 0.5057
Epoch 4/100
88/88 [==============================] - 0s 1ms/step - loss: 0.6887 - Accuracy: 0.6080
Epoch 5/100
88/88 [==============================] - 0s 1ms/step - loss: 0.6810 - Accuracy: 0.6477
Epoch 6/100
88/88 [==============================] - 0s 1ms/step - loss: 0.6641 - Accuracy: 0.7102
Epoch 7/100
88/88 [==============================] - 0s 2ms/step - loss: 0.6354 - Accuracy: 0.7045
Epoch 8/100
88/88 [==============================] - 0s 1ms/step - loss: 0.5759 - Accuracy: 0.7386
Epoch 9/100
88/88 [==============================] - 0s 1ms/step - loss: 0.5677 - Accuracy: 0.7557
Epoch 10/100
88/88 [==============================] - 0s 1ms/step - loss: 0.5374 - Accuracy: 0.7670
Epoch 11/

88/88 [==============================] - 0s 1ms/step - loss: 0.1938 - Accuracy: 0.9091
Epoch 84/100
88/88 [==============================] - 0s 1ms/step - loss: 0.2044 - Accuracy: 0.9148
Epoch 85/100
88/88 [==============================] - 0s 1ms/step - loss: 0.2153 - Accuracy: 0.8977
Epoch 86/100
88/88 [==============================] - 0s 1ms/step - loss: 0.2123 - Accuracy: 0.8977
Epoch 87/100
88/88 [==============================] - 0s 1ms/step - loss: 0.2237 - Accuracy: 0.9091
Epoch 88/100
88/88 [==============================] - 0s 1ms/step - loss: 0.2366 - Accuracy: 0.9148
Epoch 89/100
88/88 [==============================] - 0s 1ms/step - loss: 0.1867 - Accuracy: 0.9205
Epoch 90/100
88/88 [==============================] - 0s 1ms/step - loss: 0.1832 - Accuracy: 0.9318
Epoch 91/100
88/88 [==============================] - 0s 1ms/step - loss: 0.2012 - Accuracy: 0.9318
Epoch 92/100
88/88 [==============================] - 0s 1ms/step - loss: 0.1983 - Accuracy: 0.9091
Epoch 93/100


In [21]:
y_pred = model.predict(x_test)
y_pred

array([[3.24448109e-01],
       [4.01949774e-06],
       [1.09108686e-02],
       [4.17214632e-03],
       [3.49124966e-05],
       [9.99947309e-01],
       [1.00000000e+00],
       [3.32629681e-03],
       [4.73550558e-02],
       [1.23658776e-03],
       [8.94212961e-01],
       [6.41420215e-08],
       [4.83616233e-01],
       [2.29775906e-03],
       [9.98038769e-01],
       [1.04728341e-03],
       [1.34340525e-02],
       [2.12180912e-02],
       [1.31815672e-03],
       [1.00000000e+00],
       [1.29899383e-03],
       [9.99941587e-01],
       [9.99374568e-01],
       [3.32318377e-05],
       [5.89758158e-04],
       [8.06897879e-04],
       [2.01431194e-05],
       [6.20552301e-01],
       [9.19966894e-08],
       [3.47757518e-01],
       [1.00000000e+00],
       [4.83761132e-02]], dtype=float32)

In [22]:
df.iloc[:,-1].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [23]:
pd.DataFrame(y).value_counts()

0    111
1     97
dtype: int64

In [24]:
y_pred = y_pred.astype(int)

In [25]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [26]:
confusion_matrix(y_test,y_pred)

array([[22,  0],
       [ 7,  3]])

In [27]:
accuracy_score(y_test,y_pred)

0.78125